apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cksah09sp-nodejs
  janus-idp.io/tekton: cksah09sp-nodejs
  backstage.io/kubernetes-id: cksah09sp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cksah09sp-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
